[package]
name = ""
version = "1.0.0"
description = ""
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[dependencies]
axum = "0.6.20"
hyper = { version = "0.14.27", features = ["full"] }
tokio = { version = "1.32.0", features = ["full"] }
tower = "0.4.13"